project:
  type: book
  output-dir: docs

book:
  title: "Documenting Data Processing"
  author: "Sangwon Hyun"
  chapters:
    - index.Rmd
    - 00-setup.qmd
    - 01-process-seaflow.qmd
    - 02-process-seaflow-covariates.qmd
    - 03-add-onboard-covariates.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    embed-resources: true
